SELECT SKU, SKU_Description FROM cape_codd.inventory;
SELECT SKU_Description, SKU FROM cape_codd.inventory;
SELECT WarehouseID FROM cape_codd.inventory;
SELECT DISTINCT warehouseID FROM cape_codd.inventory;
SELECT WarehouseID, SKU, SKU_Description, QuantityOnHand, QuantityOnOrder FROM cape_codd.inventory;
SELECT * FROM cape_codd.inventory;
SELECT * FROM cape_codd.inventory WHERE QuantityOnHand > 0;
SELECT SKU, SKU_Description FROM cape_codd.inventory WHERE QuantityOnHand = 0;
SELECT SKU, SKU_Description, WarehouseID FROM cape_codd.inventory WHERE QuantityOnHand = 0 ORDER BY WarehouseID;
SELECT SKU, SKU_Description, WarehouseID FROM cape_codd.inventory WHERE QuantityOnHand > 0 ORDER BY WarehouseID DESC, SKU ASC;
SELECT SKU, SKU_Description, WarehouseID FROM cape_codd.inventory WHERE QuantityOnHand = 0 AND QuantityOnOrder > 0 ORDER BY WarehouseID DESC, SKU ASC;
SELECT SKU, SKU_Description, WarehouseID FROM cape_codd.inventory WHERE QuantityOnHand = 0 OR QuantityOnOrder = 0 ORDER BY WarehouseID DESC, SKU ASC;
SELECT SKU, SKU_Description, WarehouseID, QuantityOnHand FROM cape_codd.inventory WHERE QuantityOnHand > 1 AND QuantityOnHand < 10;
SELECT SKU, SKU_Description, WarehouseID, QuantityOnHand FROM cape_codd.inventory WHERE QuantityOnHand BETWEEN 1 AND 10;
SELECT DISTINCT SKU, SKU_Description FROM cape_codd.inventory WHERE SKU_Description LIKE 'Half-Dome%';
SELECT DISTINCT SKU, SKU_Description FROM cape_codd.inventory WHERE SKU_Description LIKE '%Climb%';
SELECT DISTINCT SKU, SKU_Description FROM cape_codd.inventory WHERE SKU_Description LIKE '__d%';
SELECT SUM(QuantityOnHand) AS QuantityOnHandSum, AVG(QuantityOnHand) AS Average, MIN(QuantityOnHand) AS Minimum, MAX(QuantityOnHand) AS Maximum, COUNT(QuantityOnHand) AS QuantityAmount FROM cape_codd.inventory;
SELECT WarehouseID, SUM(QuantityOnHand) AS TotalItemsOnHand FROM cape_codd.inventory GROUP BY WarehouseID ORDER BY TotalItemsOnHand DESC;
